version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - VAULT_ADDR=http://192.168.1.250:8200
      - ROLE_ID=your_role_id  # Replace with actual Role ID
      - SECRET_ID=your_secret_id  # Replace with actual Secret ID
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis_data:
