version: '3.8'

services:
  vault:
    image: vault:1.10.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": 1
            }
          },
          "disable_mlock": true,
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": true,
          "api_addr": "http://192.168.1.250:8200"
        }
      VAULT_ADDR: 'http://127.0.0.1:8200'
    volumes:
      - ./vault/data:/vault/file
    command: ["server"]

volumes:
  vault_data:
