version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - VAULT_ADDR=http://192.168.1.250:8200
      - ROLE_ID=${ROLE_ID}
      - SECRET_ID=${SECRET_ID}
    volumes:
      - configs:/configs
      - redis_data:/data
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "apt-get update && apt-get install -y curl jq && 
      mkdir -p /usr/local/etc/redis && 
      cp /configs/redis/redis.conf /usr/local/etc/redis/redis.conf && 
      redis-server /usr/local/etc/redis/redis.conf"

volumes:
  redis_data:
  configs:
    external: true
    name: configs
